const chatList = [{
    image: "/src/assets/1.jpg",
    name: "Alex",
    text: "“How are you?”",
    time: "11:49",
    unread: 1,
    messages: [
      { content: "I've been waiting to see that show asap!", time: "07:43", isMyMessage: true },
      { content: "Ahh, I can't believe you do too!", time: "07:45", isMyMessage: false },
      { content: "The trailer looks good", time: "07:45", isMyMessage: false },
      { content: "I've been waiting to watch it!!", time: "07:45", isMyMessage: false },
      { content: "😐😐😐", time: "07:46", isMyMessage: true },
      { content: "Mee too! 😊", time: "07:46", isMyMessage: true },
      { content: "We should video chat to discuss, if you're up for it!", time: "07:48", isMyMessage: false },
      { content: "Sure", time: "07:48", isMyMessage: true },
      { content: "I'm free now!", time: "07:48", isMyMessage: true },
      { content: "Awesome! I'll start a video chat with you in a few.", time: "07:49", isMyMessage: false },
    ]
  },
  {
    image: "/src/assets/2.jpg",
    name: "Jack",
    text: "“I’ll be there.”",
    time: "10:49",
    unread: 4,
    messages: [
      { content: "I've been waiting to see that show asap!", time: "07:43", isMyMessage: true },
      { content: "Ahh, I can't believe you do too!", time: "07:45", isMyMessage: false },
      { content: "The trailer looks good", time: "07:45", isMyMessage: false },
      { content: "I've been waiting to watch it!!", time: "07:45", isMyMessage: false },
      { content: "😐😐😐", time: "07:46", isMyMessage: true },
      { content: "Mee too! 😊", time: "07:46", isMyMessage: true },
      { content: "We should video chat to discuss, if you're up for it!", time: "07:48", isMyMessage: false },
      { content: "Sure", time: "07:48", isMyMessage: true },
      { content: "I'm free now!", time: "07:48", isMyMessage: true },
      { content: "Awesome! I'll start a video chat with you in a few.", time: "07:49", isMyMessage: false },
    ]
  },{
    image: "/src/assets/3.jpg",
    name: "Zack",
    text: "“How are you?”",
    time: "09:49",
    unread: 2,
    messages: [
      { content: "I've been waiting to see that show asap!", time: "07:43", isMyMessage: true },
      { content: "Ahh, I can't believe you do too!", time: "07:45", isMyMessage: false },
      { content: "The trailer looks good", time: "07:45", isMyMessage: false },
      { content: "I've been waiting to watch it!!", time: "07:45", isMyMessage: false },
      { content: "😐😐😐", time: "07:46", isMyMessage: true },
      { content: "Mee too! 😊", time: "07:46", isMyMessage: true },
      { content: "We should video chat to discuss, if you're up for it!", time: "07:48", isMyMessage: false },
      { content: "Sure", time: "07:48", isMyMessage: true },
      { content: "I'm free now!", time: "07:48", isMyMessage: true },
      { content: "Awesome! I'll start a video chat with you in a few.", time: "07:49", isMyMessage: false },
    ]
  },{
    image: "/src/assets/4.jpg",
    name: "Ava",
    text: "“How are you?”",
    time: "08:49",
    messages: [
      { content: "I've been waiting to see that show asap!", time: "07:43", isMyMessage: true },
      { content: "Ahh, I can't believe you do too!", time: "07:45", isMyMessage: false },
      { content: "The trailer looks good", time: "07:45", isMyMessage: false },
      { content: "I've been waiting to watch it!!", time: "07:45", isMyMessage: false },
      { content: "😐😐😐", time: "07:46", isMyMessage: true },
      { content: "Mee too! 😊", time: "07:46", isMyMessage: true },
      { content: "We should video chat to discuss, if you're up for it!", time: "07:48", isMyMessage: false },
      { content: "Sure", time: "07:48", isMyMessage: true },
      { content: "I'm free now!", time: "07:48", isMyMessage: true },
      { content: "Awesome! I'll start a video chat with you in a few.", time: "07:49", isMyMessage: false },
    ]
  },{
    image: "/src/assets/5.jpg",
    name: "Leon",
    text: "“How are you?”",
    time: "08:49",
    messages: [
      { content: "I've been waiting to see that show asap!", time: "07:43", isMyMessage: true },
      { content: "Ahh, I can't believe you do too!", time: "07:45", isMyMessage: false },
      { content: "The trailer looks good", time: "07:45", isMyMessage: false },
      { content: "I've been waiting to watch it!!", time: "07:45", isMyMessage: false },
      { content: "😐😐😐", time: "07:46", isMyMessage: true },
      { content: "Mee too! 😊", time: "07:46", isMyMessage: true },
      { content: "We should video chat to discuss, if you're up for it!", time: "07:48", isMyMessage: false },
      { content: "Sure", time: "07:48", isMyMessage: true },
      { content: "I'm free now!", time: "07:48", isMyMessage: true },
      { content: "Awesome! I'll start a video chat with you in a few.", time: "07:49", isMyMessage: false },
    ]
  },{
    image: "/src/assets/6.jpg",
    name: "Jennifer",
    text: "“How are you?”",
    time: "07:49",
    unread: 5,
    messages: [
      { content: "I've been waiting to see that show asap!", time: "07:43", isMyMessage: true },
      { content: "Ahh, I can't believe you do too!", time: "07:45", isMyMessage: false },
      { content: "The trailer looks good", time: "07:45", isMyMessage: false },
      { content: "I've been waiting to watch it!!", time: "07:45", isMyMessage: false },
      { content: "😐😐😐", time: "07:46", isMyMessage: true },
      { content: "Mee too! 😊", time: "07:46", isMyMessage: true },
      { content: "We should video chat to discuss, if you're up for it!", time: "07:48", isMyMessage: false },
      { content: "Sure", time: "07:48", isMyMessage: true },
      { content: "I'm free now!", time: "07:48", isMyMessage: true },
      { content: "Awesome! I'll start a video chat with you in a few.", time: "07:49", isMyMessage: false },
    ]
  },{
    image: "/src/assets/7.jpg",
    name: "Oliver",
    text: "“How are you?”",
    time: "07:49",
    messages: [
      { content: "I've been waiting to see that show asap!", time: "07:43", isMyMessage: true },
      { content: "Ahh, I can't believe you do too!", time: "07:45", isMyMessage: false },
      { content: "The trailer looks good", time: "07:45", isMyMessage: false },
      { content: "I've been waiting to watch it!!", time: "07:45", isMyMessage: false },
      { content: "😐😐😐", time: "07:46", isMyMessage: true },
      { content: "Mee too! 😊", time: "07:46", isMyMessage: true },
      { content: "We should video chat to discuss, if you're up for it!", time: "07:48", isMyMessage: false },
      { content: "Sure", time: "07:48", isMyMessage: true },
      { content: "I'm free now!", time: "07:48", isMyMessage: true },
      { content: "Awesome! I'll start a video chat with you in a few.", time: "07:49", isMyMessage: false },
    ]
  },{
    image: "/src/assets/8.jpg",
    name: "Jeslin",
    text: "“How are you?”",
    time: "06:49",
    unread: 1,
    messages: [
      { content: "I've been waiting to see that show asap!", time: "07:43", isMyMessage: true },
      { content: "Ahh, I can't believe you do too!", time: "07:45", isMyMessage: false },
      { content: "The trailer looks good", time: "07:45", isMyMessage: false },
      { content: "I've been waiting to watch it!!", time: "07:45", isMyMessage: false },
      { content: "😐😐😐", time: "07:46", isMyMessage: true },
      { content: "Mee too! 😊", time: "07:46", isMyMessage: true },
      { content: "We should video chat to discuss, if you're up for it!", time: "07:48", isMyMessage: false },
      { content: "Sure", time: "07:48", isMyMessage: true },
      { content: "I'm free now!", time: "07:48", isMyMessage: true },
      { content: "Awesome! I'll start a video chat with you in a few.", time: "07:49", isMyMessage: false },
    ]
  },
  {
    image: "/src/assets/1.jpg",
    name: "Alex",
    text: "“How are you?”",
    time: "11:49",
    unread: 1,
    messages: [
      { content: "I've been waiting to see that show asap!", time: "07:43", isMyMessage: true },
      { content: "Ahh, I can't believe you do too!", time: "07:45", isMyMessage: false },
      { content: "The trailer looks good", time: "07:45", isMyMessage: false },
      { content: "I've been waiting to watch it!!", time: "07:45", isMyMessage: false },
      { content: "😐😐😐", time: "07:46", isMyMessage: true },
      { content: "Mee too! 😊", time: "07:46", isMyMessage: true },
      { content: "We should video chat to discuss, if you're up for it!", time: "07:48", isMyMessage: false },
      { content: "Sure", time: "07:48", isMyMessage: true },
      { content: "I'm free now!", time: "07:48", isMyMessage: true },
      { content: "Awesome! I'll start a video chat with you in a few.", time: "07:49", isMyMessage: false },
    ]
  },
  {
    image: "/src/assets/2.jpg",
    name: "Jack",
    text: "“I’ll be there.”",
    time: "11:49",
    unread: 4,
    messages: [
      { content: "I've been waiting to see that show asap!", time: "07:43", isMyMessage: true },
      { content: "Ahh, I can't believe you do too!", time: "07:45", isMyMessage: false },
      { content: "The trailer looks good", time: "07:45", isMyMessage: false },
      { content: "I've been waiting to watch it!!", time: "07:45", isMyMessage: false },
      { content: "😐😐😐", time: "07:46", isMyMessage: true },
      { content: "Mee too! 😊", time: "07:46", isMyMessage: true },
      { content: "We should video chat to discuss, if you're up for it!", time: "07:48", isMyMessage: false },
      { content: "Sure", time: "07:48", isMyMessage: true },
      { content: "I'm free now!", time: "07:48", isMyMessage: true },
      { content: "Awesome! I'll start a video chat with you in a few.", time: "07:49", isMyMessage: false },
    ]
  },{
    image: "/src/assets/3.jpg",
    name: "Zack",
    text: "“How are you?”",
    time: "11:49",
    unread: 2,
    messages: [
      { content: "I've been waiting to see that show asap!", time: "07:43", isMyMessage: true },
      { content: "Ahh, I can't believe you do too!", time: "07:45", isMyMessage: false },
      { content: "The trailer looks good", time: "07:45", isMyMessage: false },
      { content: "I've been waiting to watch it!!", time: "07:45", isMyMessage: false },
      { content: "😐😐😐", time: "07:46", isMyMessage: true },
      { content: "Mee too! 😊", time: "07:46", isMyMessage: true },
      { content: "We should video chat to discuss, if you're up for it!", time: "07:48", isMyMessage: false },
      { content: "Sure", time: "07:48", isMyMessage: true },
      { content: "I'm free now!", time: "07:48", isMyMessage: true },
      { content: "Awesome! I'll start a video chat with you in a few.", time: "07:49", isMyMessage: false },
    ]
  },{
    image: "/src/assets/4.jpg",
    name: "Ava",
    text: "“How are you?”",
    time: "11:49",
    messages: [
      { content: "I've been waiting to see that show asap!", time: "07:43", isMyMessage: true },
      { content: "Ahh, I can't believe you do too!", time: "07:45", isMyMessage: false },
      { content: "The trailer looks good", time: "07:45", isMyMessage: false },
      { content: "I've been waiting to watch it!!", time: "07:45", isMyMessage: false },
      { content: "😐😐😐", time: "07:46", isMyMessage: true },
      { content: "Mee too! 😊", time: "07:46", isMyMessage: true },
      { content: "We should video chat to discuss, if you're up for it!", time: "07:48", isMyMessage: false },
      { content: "Sure", time: "07:48", isMyMessage: true },
      { content: "I'm free now!", time: "07:48", isMyMessage: true },
      { content: "Awesome! I'll start a video chat with you in a few.", time: "07:49", isMyMessage: false },
    ]
  },{
    image: "/src/assets/5.jpg",
    name: "Leon",
    text: "“How are you?”",
    time: "11:49",
    messages: [
      { content: "I've been waiting to see that show asap!", time: "07:43", isMyMessage: true },
      { content: "Ahh, I can't believe you do too!", time: "07:45", isMyMessage: false },
      { content: "The trailer looks good", time: "07:45", isMyMessage: false },
      { content: "I've been waiting to watch it!!", time: "07:45", isMyMessage: false },
      { content: "😐😐😐", time: "07:46", isMyMessage: true },
      { content: "Mee too! 😊", time: "07:46", isMyMessage: true },
      { content: "We should video chat to discuss, if you're up for it!", time: "07:48", isMyMessage: false },
      { content: "Sure", time: "07:48", isMyMessage: true },
      { content: "I'm free now!", time: "07:48", isMyMessage: true },
      { content: "Awesome! I'll start a video chat with you in a few.", time: "07:49", isMyMessage: false },
    ]
  },{
    image: "/src/assets/6.jpg",
    name: "Jennifer",
    text: "“How are you?”",
    time: "11:49",
    unread: 5,
    messages: [
      { content: "I've been waiting to see that show asap!", time: "07:43", isMyMessage: true },
      { content: "Ahh, I can't believe you do too!", time: "07:45", isMyMessage: false },
      { content: "The trailer looks good", time: "07:45", isMyMessage: false },
      { content: "I've been waiting to watch it!!", time: "07:45", isMyMessage: false },
      { content: "😐😐😐", time: "07:46", isMyMessage: true },
      { content: "Mee too! 😊", time: "07:46", isMyMessage: true },
      { content: "We should video chat to discuss, if you're up for it!", time: "07:48", isMyMessage: false },
      { content: "Sure", time: "07:48", isMyMessage: true },
      { content: "I'm free now!", time: "07:48", isMyMessage: true },
      { content: "Awesome! I'll start a video chat with you in a few.", time: "07:49", isMyMessage: false },
    ]
  },{
    image: "/src/assets/7.jpg",
    name: "Oliver",
    text: "“How are you?”",
    time: "11:49",
    messages: [
      { content: "I've been waiting to see that show asap!", time: "07:43", isMyMessage: true },
      { content: "Ahh, I can't believe you do too!", time: "07:45", isMyMessage: false },
      { content: "The trailer looks good", time: "07:45", isMyMessage: false },
      { content: "I've been waiting to watch it!!", time: "07:45", isMyMessage: false },
      { content: "😐😐😐", time: "07:46", isMyMessage: true },
      { content: "Mee too! 😊", time: "07:46", isMyMessage: true },
      { content: "We should video chat to discuss, if you're up for it!", time: "07:48", isMyMessage: false },
      { content: "Sure", time: "07:48", isMyMessage: true },
      { content: "I'm free now!", time: "07:48", isMyMessage: true },
      { content: "Awesome! I'll start a video chat with you in a few.", time: "07:49", isMyMessage: false },
    ]
  },{
    image: "/src/assets/8.jpg",
    name: "Jeslin",
    text: "“How are you?”",
    time: "11:49",
    unread: 1,
    messages: [
      { content: "I've been waiting to see that show asap!", time: "07:43", isMyMessage: true },
      { content: "Ahh, I can't believe you do too!", time: "07:45", isMyMessage: false },
      { content: "The trailer looks good", time: "07:45", isMyMessage: false },
      { content: "I've been waiting to watch it!!", time: "07:45", isMyMessage: false },
      { content: "😐😐😐", time: "07:46", isMyMessage: true },
      { content: "Mee too! 😊", time: "07:46", isMyMessage: true },
      { content: "We should video chat to discuss, if you're up for it!", time: "07:48", isMyMessage: false },
      { content: "Sure", time: "07:48", isMyMessage: true },
      { content: "I'm free now!", time: "07:48", isMyMessage: true },
      { content: "Awesome! I'll start a video chat with you in a few.", time: "07:49", isMyMessage: false },
    ],
  }]

export default chatList